# Generated by Django 3.1.2 on 2020-12-01 06:36

import aplicacion.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cli_Rut', models.CharField(max_length=30, unique=True, verbose_name='Rut')),
                ('cli_Nombre', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('cli_Apellidos', models.CharField(blank=True, max_length=30, verbose_name='Apellidos')),
                ('cli_Edad', models.IntegerField(blank=True, default='0', null=True, verbose_name='Edad')),
                ('cli_Nacionalidad', models.CharField(blank=True, max_length=30, verbose_name='Nacionalidad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('cli_Telefono', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('codregistro', models.CharField(blank=True, default='000000', max_length=6)),
                ('funcionario', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_ciudad', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_comuna', models.CharField(default='', max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond_rut', models.CharField(max_length=14, unique=True, verbose_name='Rut')),
                ('cond_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('cond_apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('cond_edad', models.IntegerField(default='0', verbose_name='Edad')),
                ('cond_nacionalidad', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('cond_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('cond_telefono', models.CharField(max_length=12, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('descripcioncontacto', models.TextField()),
                ('correoaenviar', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Departamento', models.CharField(max_length=30)),
                ('Numero_propiedad', models.IntegerField(default='0', null=True)),
                ('Descripcion_departamento', models.CharField(default='', max_length=200)),
                ('Direccion_departamento', models.CharField(default='', max_length=200)),
                ('habitaciones', models.IntegerField(default='0', null=True)),
                ('Baños', models.IntegerField(default='0', null=True)),
                ('Calefaccion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('Internet', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('Amoblado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('Televicion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('Imagen_Recinto', models.ImageField(blank=True, default='/static/img/logo.PNG', null=True, upload_to='departamento/')),
                ('Imagen_Entorno', models.ImageField(blank=True, null=True, upload_to='')),
                ('Valor_Diario', models.IntegerField(default='0')),
                ('Disponible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('dividendo', models.IntegerField(default='0')),
                ('contribucion', models.IntegerField(default='0')),
                ('comuna', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacion.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparacion', models.CharField(default='', max_length=100)),
                ('mejoramiento', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_multa', models.CharField(default='', max_length=100)),
                ('monto_multa', models.IntegerField(default='0', verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tour', models.CharField(default='', max_length=100)),
                ('categoria', models.CharField(choices=[('Tour City', 'Tour City'), ('Turismo Aventura', 'Turismo Aventura')], default='Tour City', max_length=100)),
                ('comestible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=100)),
                ('valor_tour', models.IntegerField(default='0', verbose_name='Valor')),
                ('imagen_tour', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=14, unique=True, verbose_name='Patente')),
                ('color_vehiculo', models.CharField(max_length=30, verbose_name='Color Vehiculo')),
                ('cant_puerta', models.IntegerField(default='0', null=True, verbose_name='Puertas')),
                ('aire_acondicionado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=30, verbose_name='Color Vehiculo')),
                ('cant_asiento', models.IntegerField(default='0', null=True, verbose_name='Asiento')),
                ('disponibilidad_vehi', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=30, verbose_name='Color Vehiculo')),
                ('imagen_vehiculo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('modelo', models.CharField(default='', max_length=30)),
                ('marca', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_servicio', models.CharField(max_length=20, verbose_name='Descripcion Servicios')),
                ('direccion_reunion', models.CharField(max_length=50, verbose_name='Reunion')),
                ('direccion_destino', models.CharField(max_length=50, verbose_name='Desatino')),
                ('fecha_encuentro', models.DateField(default=datetime.date.today, verbose_name='Fecha encuentro')),
                ('fecha_termino_servicio', models.DateField(default=datetime.date.today, verbose_name='Fecha Termino')),
                ('valor_servicio', models.IntegerField(default='0', verbose_name='Valor')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.conductor')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Reserva', models.CharField(default=aplicacion.models.random_string, max_length=5, unique=True)),
                ('Fecha_Reserva_Inicio', models.DateField(blank=True, default=datetime.date.today)),
                ('Fecha_Reserva_Termino', models.DateField(blank=True, default=datetime.date.today)),
                ('Cantidad_Dias', models.IntegerField(default='0', verbose_name='Valor')),
                ('Estado_Reserva', models.BooleanField(default=False)),
                ('check', models.CharField(choices=[('NoCheck', 'NoCheck'), ('CheckIn', 'CheckIn'), ('CheckOut', 'CheckOut')], default='No Check', max_length=100)),
                ('total_cobrar', models.FloatField(default='0')),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacion.departamento')),
                ('multa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.multa')),
                ('servicioextra', models.ManyToManyField(blank=True, null=True, to='aplicacion.ServicioExtra')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='inventario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacion.inventario'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculo',
            field=models.ManyToManyField(to='aplicacion.Vehiculo'),
        ),
        migrations.CreateModel(
            name='Acompañante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acom_rut', models.CharField(max_length=14, unique=True, verbose_name='Rut')),
                ('acom_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('acom_apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('acom_edad', models.IntegerField(default='0', null=True, verbose_name='Edad')),
                ('acom_nacionalidad', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('acom_email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('acom_telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
