# Generated by Django 3.1.2 on 2020-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='estado_multa',
            field=models.BooleanField(default=False),
        ),
    ]
