# Generated by Django 3.1.2 on 2020-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='clientes',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Estado_Reserva',
            field=models.CharField(choices=[('0', 'VIGENTE'), ('1', 'CONCRETADA')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Termino',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicioextra',
            field=models.ManyToManyField(blank=True, default='None', null=True, to='aplicacion.ServicioExtra'),
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='TarjetaCredito',
        ),
    ]
