# Generated by Django 3.1.2 on 2020-12-03 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_multa_estado_multa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='multa',
        ),
        migrations.AddField(
            model_name='multa',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.reserva'),
        ),
    ]
