# Generated by Django 3.1.2 on 2020-10-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20201025_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Estado_Reserva',
            field=models.CharField(choices=[('0', 'VIGENTE'), ('1', 'CONCRETADA')], default='', max_length=100),
        ),
    ]
