# Generated by Django 3.1.2 on 2020-11-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20201104_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cliente',
            new_name='user',
        ),
    ]
