# Generated by Django 3.1.2 on 2020-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_departamento_cantidad_habitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Cantidad_Dias',
            field=models.IntegerField(default='0', verbose_name='Valor'),
        ),
    ]
