# Generated by Django 3.1.2 on 2020-11-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20201104_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='Check_in',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='Check_out',
        ),
    ]
