# Generated by Django 3.1.2 on 2020-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_reserva_cantidad_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_cobrar',
            field=models.FloatField(default='0'),
        ),
    ]
