# Generated by Django 3.1.2 on 2020-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_reserva_total_cobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='check',
            field=models.CharField(choices=[('No Check', 'No Check'), ('Check In', 'Check In'), ('Check Out', 'Check Out')], default='No Check', max_length=100),
        ),
    ]
