# Generated by Django 3.1.2 on 2020-11-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20201105_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Amoblado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Calefaccion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Disponible',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Internet',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Televicion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
    ]
