# Generated by Django 3.1.2 on 2020-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20201025_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Termino',
            field=models.DateField(blank=True),
        ),
    ]
