# Generated by Django 3.1.2 on 2020-10-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_auto_20201026_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicioextra',
            field=models.ManyToManyField(blank=True, default='None', null=True, to='aplicacion.ServicioExtra'),
        ),
    ]
