# Generated by Django 3.1.2 on 2020-11-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20201122_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Cantidad_Dias',
            field=models.IntegerField(default='1', verbose_name='Valor'),
        ),
    ]
