# Generated by Django 3.1.2 on 2020-11-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20201122_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Entorno',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Recinto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Cantidad_Dias',
            field=models.IntegerField(default='0', verbose_name='Valor'),
        ),
    ]
