# Generated by Django 3.1.2 on 2020-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20201111_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicioextra',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacion.ServicioExtra'),
        ),
    ]
