# Generated by Django 3.1.2 on 2020-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20201112_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Estado_Reserva',
            field=models.BooleanField(default=False),
        ),
    ]
