# Generated by Django 3.1.2 on 2020-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20201123_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Entorno',
            field=models.ImageField(blank=True, null=True, upload_to='departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Recinto',
            field=models.ImageField(blank=True, null=True, upload_to='departamento'),
        ),
    ]
