# Generated by Django 3.1.2 on 2020-11-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_auto_20201123_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Entorno',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Recinto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
