# Generated by Django 3.1.2 on 2020-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_auto_20201123_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Imagen_Recinto',
            field=models.ImageField(blank=True, default='/static/img/logo.PNG', null=True, upload_to='departamento/'),
        ),
    ]
