# Generated by Django 3.1.2 on 2020-11-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_auto_20201123_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='gasto',
        ),
        migrations.AddField(
            model_name='departamento',
            name='contribucion',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='dividendo',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
