# Generated by Django 3.1.2 on 2020-11-24 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_auto_20201123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompañante',
            name='acom_edad',
            field=models.IntegerField(default='0', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cond_edad',
            field=models.IntegerField(default='0', verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Baños',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Numero_propiedad',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Valor_Diario',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='habitaciones',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Inicio',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicioextra',
            name='valor_servicio',
            field=models.IntegerField(default='0', verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cli_Edad',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cant_asiento',
            field=models.IntegerField(default='0', null=True, verbose_name='Asiento'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cant_puerta',
            field=models.IntegerField(default='0', null=True, verbose_name='Puertas'),
        ),
    ]
