# Generated by Django 3.1.2 on 2020-11-24 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_auto_20201123_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Reserva_Termino',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicioextra',
            name='fecha_encuentro',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha encuentro'),
        ),
        migrations.AlterField(
            model_name='servicioextra',
            name='fecha_termino_servicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Termino'),
        ),
    ]
