# Generated by Django 3.1.2 on 2020-11-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_auto_20201112_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='Codigo_Reserva',
        ),
    ]
