# Generated by Django 3.1.2 on 2020-11-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_auto_20201123_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Amoblado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Internet',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Televicion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='categoria',
            field=models.CharField(choices=[('Tour City', 'Tour City'), ('Turismo Aventura', 'Turismo Aventura')], default='Tour City', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='comestible',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='aire_acondicionado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=30, verbose_name='Color Vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='disponibilidad_vehi',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=30, verbose_name='Color Vehiculo'),
        ),
    ]
