# Generated by Django 3.1.2 on 2020-11-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_auto_20201123_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_multa', models.CharField(default='', max_length=100)),
                ('monto_multa', models.IntegerField(default='0', verbose_name='Valor')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='multa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.multa'),
        ),
    ]
