# Generated by Django 3.1.2 on 2020-11-13 03:26

import aplicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_auto_20201112_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompañante',
            name='acom_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Codigo_Reserva',
            field=models.CharField(default=aplicacion.models.random_string, max_length=5, unique=True),
        ),
    ]
